// DO NOT EDIT
// Generated by JFlex 1.8.1 http://jflex.de/
// source: C:/Users/gille/Documents/GitHub/O3/app/src/main/java/com/gfabre/android/o3/ScriptLexer.flex

package com.gfabre.android.o3;

/* JFlex Script Lexical Analyzer definition file : yylex() will return script tokens  */
import java_cup.runtime.*;
import java.lang.String;
import java.lang.Double;

/**
 * This class defines the Script Lexical Analyzer
 */

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class ScriptLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\12\u1f00\1\u2000\1\u2100\1\u2200\1\u1f00\1\u2300"+
    "\1\u2400\2\u1f00\31\u0100\1\u2500\121\u0100\1\u2600\4\u0100\1\u2700"+
    "\1\u0100\1\u2800\1\u2900\1\u2a00\1\u2b00\1\u2c00\1\u2d00\53\u0100"+
    "\1\u2e00\41\u1f00\1\u0100\1\u2f00\1\u3000\1\u0100\1\u3100\1\u3200"+
    "\1\u3300\1\u3400\1\u3500\1\u3600\1\u3700\1\u3800\3\u1f00\1\u3900"+
    "\1\u3a00\1\u3b00\1\u3c00\1\u3d00\3\u1f00\1\u3e00\1\u3f00\4\u1f00"+
    "\1\u4000\11\u1f00\3\u0100\1\u4100\1\u4200\13\u1f00\4\u0100\1\u4300"+
    "\63\u1f00\2\u0100\1\u4400\4\u1f00\1\u4500\100\u1f00\1\u4600\40\u1f00"+
    "\1\u4700\1\u4800\1\u1f00\1\u4900\1\u4a00\1\u4b00\1\u4c00\26\u1f00"+
    "\1\u4d00\21\u1f00\246\u0100\1\u4e00\20\u0100\1\u4f00\1\u5000\77\u1f00"+
    "\2\u0100\1\u5000\u0b05\u1f00\1\u5100\1\u5200\u02fe\u1f00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\16\0\4\3"+
    "\1\1\1\6\1\7\1\3\1\10\1\11\4\3\1\12"+
    "\1\13\1\3\1\14\1\15\1\16\3\17\1\20\6\17"+
    "\2\3\1\21\1\22\1\23\1\24\1\3\3\10\1\25"+
    "\1\26\25\10\1\27\1\3\1\30\1\3\1\31\1\3"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\10\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\1\10\1\51\1\52\1\53\1\54\1\55\1\56\1\57"+
    "\1\10\1\60\4\3\41\0\2\3\4\10\4\3\1\10"+
    "\2\3\1\0\7\3\1\10\4\3\1\10\5\3\27\10"+
    "\1\3\37\10\1\3\u01ca\10\4\3\14\10\16\3\5\10"+
    "\7\3\1\10\1\3\1\10\21\3\160\0\5\10\1\3"+
    "\2\10\2\3\4\10\10\3\1\10\1\3\3\10\1\3"+
    "\1\10\1\3\24\10\1\3\123\10\1\3\213\10\1\3"+
    "\5\0\2\3\236\10\11\3\46\10\2\3\1\10\7\3"+
    "\47\10\7\3\1\10\1\3\55\0\1\3\1\0\1\3"+
    "\2\0\1\3\2\0\1\3\1\0\10\3\33\10\5\3"+
    "\3\10\15\3\5\0\6\3\1\10\4\3\13\0\5\3"+
    "\53\10\37\0\4\3\2\10\1\0\143\10\1\3\1\10"+
    "\10\0\1\3\6\0\2\10\2\0\1\3\4\0\2\10"+
    "\12\0\3\10\2\3\1\10\17\3\1\0\1\10\1\0"+
    "\36\10\33\0\2\3\131\10\13\0\1\10\16\3\12\0"+
    "\41\10\11\0\2\10\4\3\1\10\5\3\26\10\4\0"+
    "\1\10\11\0\1\10\3\0\1\10\5\0\22\3\31\10"+
    "\3\0\104\3\1\10\1\3\13\10\67\3\33\0\1\3"+
    "\4\0\66\10\3\0\1\10\22\0\1\10\7\0\12\10"+
    "\2\0\2\3\12\0\1\3\7\10\1\3\7\10\1\3"+
    "\3\0\1\3\10\10\2\3\2\10\2\3\26\10\1\3"+
    "\7\10\1\3\1\10\3\3\4\10\2\3\1\0\1\10"+
    "\7\0\2\3\2\0\2\3\3\0\1\10\10\3\1\0"+
    "\4\3\2\10\1\3\3\10\2\0\2\3\12\0\4\10"+
    "\7\3\1\10\5\3\3\0\1\3\6\10\4\3\2\10"+
    "\2\3\26\10\1\3\7\10\1\3\2\10\1\3\2\10"+
    "\1\3\2\10\2\3\1\0\1\3\5\0\4\3\2\0"+
    "\2\3\3\0\3\3\1\0\7\3\4\10\1\3\1\10"+
    "\7\3\14\0\3\10\1\0\13\3\3\0\1\3\11\10"+
    "\1\3\3\10\1\3\26\10\1\3\7\10\1\3\2\10"+
    "\1\3\5\10\2\3\1\0\1\10\10\0\1\3\3\0"+
    "\1\3\3\0\2\3\1\10\17\3\2\10\2\0\2\3"+
    "\12\0\1\3\1\10\17\3\3\0\1\3\10\10\2\3"+
    "\2\10\2\3\26\10\1\3\7\10\1\3\2\10\1\3"+
    "\5\10\2\3\1\0\1\10\7\0\2\3\2\0\2\3"+
    "\3\0\10\3\2\0\4\3\2\10\1\3\3\10\2\0"+
    "\2\3\12\0\1\3\1\10\20\3\1\0\1\10\1\3"+
    "\6\10\3\3\3\10\1\3\4\10\3\3\2\10\1\3"+
    "\1\10\1\3\2\10\3\3\2\10\3\3\3\10\3\3"+
    "\14\10\4\3\5\0\3\3\3\0\1\3\4\0\2\3"+
    "\1\10\6\3\1\0\16\3\12\0\11\3\1\10\7\3"+
    "\3\0\1\3\10\10\1\3\3\10\1\3\27\10\1\3"+
    "\12\10\1\3\5\10\3\3\1\10\7\0\1\3\3\0"+
    "\1\3\4\0\7\3\2\0\1\3\2\10\6\3\2\10"+
    "\2\0\2\3\12\0\22\3\2\0\1\3\10\10\1\3"+
    "\3\10\1\3\27\10\1\3\12\10\1\3\5\10\2\3"+
    "\1\0\1\10\7\0\1\3\3\0\1\3\4\0\7\3"+
    "\2\0\7\3\1\10\1\3\2\10\2\0\2\3\12\0"+
    "\1\3\2\10\17\3\2\0\1\3\10\10\1\3\3\10"+
    "\1\3\51\10\2\3\1\10\7\0\1\3\3\0\1\3"+
    "\4\0\1\10\10\3\1\0\10\3\2\10\2\0\2\3"+
    "\12\0\12\3\6\10\2\3\2\0\1\3\22\10\3\3"+
    "\30\10\1\3\11\10\1\3\1\10\2\3\7\10\3\3"+
    "\1\0\4\3\6\0\1\3\1\0\1\3\10\0\22\3"+
    "\2\0\15\3\60\10\1\0\2\10\7\0\4\3\10\10"+
    "\10\0\1\3\12\0\47\3\2\10\1\3\1\10\2\3"+
    "\2\10\1\3\1\10\2\3\1\10\6\3\4\10\1\3"+
    "\7\10\1\3\3\10\1\3\1\10\1\3\1\10\2\3"+
    "\2\10\1\3\4\10\1\0\2\10\6\0\1\3\2\0"+
    "\1\10\2\3\5\10\1\3\1\10\1\3\6\0\2\3"+
    "\12\0\2\3\4\10\40\3\1\10\27\3\2\0\6\3"+
    "\12\0\13\3\1\0\1\3\1\0\1\3\1\0\4\3"+
    "\2\0\10\10\1\3\44\10\4\3\24\0\1\3\2\0"+
    "\5\10\13\0\1\3\44\0\11\3\1\0\71\3\53\10"+
    "\24\0\1\10\12\0\6\3\6\10\4\0\4\10\3\0"+
    "\1\10\3\0\2\10\7\0\3\10\4\0\15\10\14\0"+
    "\1\10\17\0\2\3\46\10\1\3\1\10\5\3\1\10"+
    "\2\3\53\10\1\3\115\10\1\3\4\10\2\3\7\10"+
    "\1\3\1\10\1\3\4\10\2\3\51\10\1\3\4\10"+
    "\2\3\41\10\1\3\4\10\2\3\7\10\1\3\1\10"+
    "\1\3\4\10\2\3\17\10\1\3\71\10\1\3\4\10"+
    "\2\3\103\10\2\3\3\0\40\3\20\10\20\3\125\10"+
    "\14\3\u016c\10\2\3\21\10\1\3\32\10\5\3\113\10"+
    "\3\3\3\10\17\3\15\10\1\3\4\10\3\0\13\3"+
    "\22\10\3\0\13\3\22\10\2\0\14\3\15\10\1\3"+
    "\3\10\1\3\2\0\14\3\64\10\40\0\3\3\1\10"+
    "\3\3\2\10\1\0\2\3\12\0\41\3\3\0\2\3"+
    "\12\0\6\3\130\10\10\3\51\10\1\0\1\10\5\3"+
    "\106\10\12\3\35\10\3\3\14\0\4\3\14\0\12\3"+
    "\12\0\36\10\2\3\5\10\13\3\54\10\4\3\21\0"+
    "\7\10\2\0\6\3\12\0\46\3\27\10\5\0\4\3"+
    "\65\10\12\0\1\3\35\0\2\3\13\0\6\3\12\0"+
    "\15\3\1\10\130\3\5\0\57\10\21\0\7\10\4\3"+
    "\12\0\21\3\11\0\14\3\3\0\36\10\15\0\2\10"+
    "\12\0\54\10\16\0\14\3\44\10\24\0\10\3\12\0"+
    "\3\3\3\10\12\0\44\10\122\3\3\0\1\3\25\0"+
    "\4\10\1\0\4\10\3\0\2\10\11\3\300\10\47\0"+
    "\25\3\4\0\26\10\2\3\6\10\2\3\46\10\2\3"+
    "\6\10\2\3\10\10\1\3\1\10\1\3\1\10\1\3"+
    "\1\10\1\3\37\10\2\3\65\10\1\3\7\10\1\3"+
    "\1\10\3\3\3\10\1\3\7\10\3\3\4\10\2\3"+
    "\6\10\4\3\15\10\5\3\3\10\1\3\7\10\16\3"+
    "\5\0\32\3\5\0\20\3\2\10\23\3\1\10\13\3"+
    "\5\0\5\3\6\0\1\3\1\10\15\3\1\10\20\3"+
    "\15\10\3\3\33\10\25\3\15\0\4\3\1\0\3\3"+
    "\14\0\21\3\1\10\4\3\1\10\2\3\12\10\1\3"+
    "\1\10\3\3\5\10\6\3\1\10\1\3\1\10\1\3"+
    "\1\10\1\3\4\10\1\3\13\10\2\3\4\10\5\3"+
    "\5\10\4\3\1\10\21\3\51\10\u0177\3\57\10\1\3"+
    "\57\10\1\3\205\10\6\3\4\10\3\0\2\10\14\3"+
    "\46\10\1\3\1\10\5\3\1\10\2\3\70\10\7\3"+
    "\1\10\17\3\1\0\27\10\11\3\7\10\1\3\7\10"+
    "\1\3\7\10\1\3\7\10\1\3\7\10\1\3\7\10"+
    "\1\3\7\10\1\3\7\10\1\3\40\0\57\3\1\10"+
    "\325\3\3\10\31\3\11\10\6\0\1\3\5\10\2\3"+
    "\5\10\4\3\126\10\2\3\2\0\2\3\3\10\1\3"+
    "\132\10\1\3\4\10\5\3\51\10\3\3\136\10\21\3"+
    "\33\10\65\3\306\10\112\3\315\10\63\3\215\10\103\3"+
    "\56\10\2\3\15\10\3\3\20\10\12\0\2\10\24\3"+
    "\57\10\1\0\4\3\12\0\1\3\31\10\7\3\1\0"+
    "\120\10\2\0\45\3\11\10\2\3\147\10\2\3\4\10"+
    "\1\3\4\10\14\3\13\10\115\3\12\10\1\0\3\10"+
    "\1\0\4\10\1\0\27\10\5\0\20\3\1\10\7\3"+
    "\64\10\14\3\2\0\62\10\21\0\13\3\12\0\6\3"+
    "\22\0\6\10\3\3\1\10\4\3\12\0\34\10\10\0"+
    "\2\3\27\10\15\0\14\3\35\10\3\3\4\0\57\10"+
    "\16\0\16\3\1\10\12\0\46\3\51\10\16\0\11\3"+
    "\3\10\1\0\10\10\2\0\2\3\12\0\6\3\27\10"+
    "\3\3\1\10\1\0\4\3\60\10\1\0\1\10\3\0"+
    "\2\10\2\0\5\10\2\0\1\10\1\0\1\10\30\3"+
    "\3\10\2\3\13\10\5\0\2\3\3\10\2\0\12\3"+
    "\6\10\2\3\6\10\2\3\6\10\11\3\7\10\1\3"+
    "\7\10\221\3\43\10\10\0\1\3\2\0\2\3\12\0"+
    "\6\3\244\10\14\3\27\10\4\3\61\10\4\3\156\10"+
    "\2\3\152\10\46\3\7\10\14\3\5\10\5\3\1\10"+
    "\1\0\12\10\1\3\15\10\1\3\5\10\1\3\1\10"+
    "\1\3\2\10\1\3\2\10\1\3\154\10\41\3\153\10"+
    "\22\3\100\10\2\3\66\10\50\3\15\10\3\3\20\0"+
    "\20\3\7\0\14\3\2\10\30\3\3\10\31\3\1\10"+
    "\6\3\5\10\1\3\207\10\2\3\1\0\4\3\1\10"+
    "\13\3\12\0\7\3\32\10\4\3\1\10\1\3\32\10"+
    "\13\3\131\10\3\3\6\10\2\3\6\10\2\3\6\10"+
    "\2\3\3\10\3\3\2\10\3\3\2\10\22\3\3\0"+
    "\4\3\14\10\1\3\32\10\1\3\23\10\1\3\2\10"+
    "\1\3\17\10\2\3\16\10\42\3\173\10\105\3\65\10"+
    "\210\3\1\0\202\3\35\10\3\3\61\10\57\3\37\10"+
    "\21\3\33\10\65\3\36\10\2\3\44\10\4\3\10\10"+
    "\1\3\5\10\52\3\236\10\2\3\12\0\126\3\6\10"+
    "\2\3\1\10\1\3\54\10\1\3\2\10\3\3\1\10"+
    "\2\3\27\10\252\3\26\10\12\3\32\10\106\3\70\10"+
    "\6\3\2\10\100\3\1\10\3\0\1\3\2\0\5\3"+
    "\4\0\4\10\1\3\3\10\1\3\33\10\4\3\3\0"+
    "\4\3\1\0\40\3\35\10\203\3\66\10\12\3\26\10"+
    "\12\3\23\10\215\3\111\10\267\3\3\0\65\10\17\0"+
    "\37\3\12\0\20\3\3\0\55\10\13\0\2\3\1\0"+
    "\22\3\31\10\7\3\12\0\6\3\3\0\44\10\16\0"+
    "\1\3\12\0\100\3\3\0\60\10\16\0\4\10\13\3"+
    "\12\0\246\3\53\10\15\0\10\3\12\0\66\3\157\10"+
    "\221\3\143\10\235\3\57\10\321\3\71\10\307\3\105\10"+
    "\13\3\1\10\56\0\20\3\4\0\15\10\140\3\2\10"+
    "\u0163\3\5\0\3\3\26\0\2\3\7\0\36\3\4\0"+
    "\224\3\3\0\273\3\125\10\1\3\107\10\1\3\2\10"+
    "\2\3\1\10\2\3\2\10\2\3\4\10\1\3\14\10"+
    "\1\3\1\10\1\3\7\10\1\3\101\10\1\3\4\10"+
    "\2\3\10\10\1\3\7\10\1\3\34\10\1\3\4\10"+
    "\1\3\5\10\1\3\1\10\3\3\7\10\1\3\u0154\10"+
    "\2\3\31\10\1\3\31\10\1\3\37\10\1\3\31\10"+
    "\1\3\37\10\1\3\31\10\1\3\37\10\1\3\31\10"+
    "\1\3\37\10\1\3\31\10\1\3\10\10\2\3\62\0"+
    "\4\10\1\3\33\10\1\3\2\10\1\3\1\10\2\3"+
    "\1\10\1\3\12\10\1\3\4\10\1\3\1\10\1\3"+
    "\1\10\6\3\1\10\4\3\1\10\1\3\1\10\1\3"+
    "\1\10\1\3\3\10\1\3\2\10\1\3\1\10\2\3"+
    "\1\10\1\3\1\10\1\3\1\10\1\3\1\10\1\3"+
    "\1\10\1\3\2\10\1\3\1\10\2\3\4\10\1\3"+
    "\7\10\1\3\4\10\1\3\4\10\1\3\1\10\1\3"+
    "\12\10\1\3\21\10\5\3\3\10\1\3\5\10\1\3"+
    "\21\10\104\3\327\10\51\3\65\10\13\3\336\10\343\3"+
    "\1\0\36\3\140\0\200\3\360\0\20\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[21248];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\7\1\1\3\21\1\1\0\1\4"+
    "\1\0\2\5\2\6\2\7\2\10\1\0\1\3\2\11"+
    "\1\0\1\2\1\0\2\12\3\0\2\13\2\0\1\14"+
    "\14\0\1\15\15\0\1\16\4\0\1\3\2\17\2\20"+
    "\2\21\2\22\1\23\6\0\1\24\10\0\1\25\11\0"+
    "\1\26\1\0\1\2\1\27\4\0\1\30\1\31\1\32"+
    "\2\0\1\33\3\0\1\34\1\0\1\35\5\0\1\36"+
    "\2\0\1\37\1\40\2\0\1\41\3\0\1\42\6\0"+
    "\1\43\1\44\1\45\2\0\1\46\1\0\1\47\3\0"+
    "\1\50\5\0\1\51\1\0\1\52\2\0\1\53\14\0"+
    "\1\54\3\0\1\55\1\56\6\0\1\57\1\60\1\61"+
    "\4\0\1\62\2\0\1\63\1\64\1\65\1\0\1\66";

  private static int [] zzUnpackAction() {
    int [] result = new int[228];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\61\0\142\0\223\0\304\0\365\0\u0126"+
    "\0\u0157\0\u0188\0\u01b9\0\u01ea\0\u021b\0\u024c\0\u027d\0\u02ae"+
    "\0\u02df\0\u0310\0\u0341\0\u0372\0\u03a3\0\u03d4\0\u0405\0\u0436"+
    "\0\u0467\0\u0498\0\u04c9\0\u04fa\0\u052b\0\u055c\0\u058d\0\u05be"+
    "\0\61\0\u05ef\0\61\0\u0620\0\61\0\u0651\0\61\0\u0682"+
    "\0\u0188\0\u06b3\0\61\0\u06e4\0\u0715\0\u0746\0\u0777\0\61"+
    "\0\u07a8\0\u07d9\0\u080a\0\u083b\0\61\0\u086c\0\u089d\0\u08ce"+
    "\0\u08ff\0\u0930\0\u0961\0\u0992\0\u09c3\0\u09f4\0\u0a25\0\u0a56"+
    "\0\u0a87\0\u0ab8\0\u0ae9\0\u0b1a\0\u0b4b\0\61\0\u0b7c\0\u0bad"+
    "\0\u0bde\0\u0c0f\0\u0c40\0\u0c71\0\u0ca2\0\u0cd3\0\u0d04\0\u0d35"+
    "\0\u0d66\0\u0d97\0\u0dc8\0\u055c\0\u0df9\0\u0e2a\0\u0e5b\0\u0e8c"+
    "\0\u0e8c\0\61\0\u0ebd\0\61\0\u0eee\0\61\0\u0f1f\0\61"+
    "\0\u0f50\0\u08ce\0\u0f81\0\u0fb2\0\u0fe3\0\u1014\0\u1045\0\u1076"+
    "\0\u10a7\0\u10d8\0\u1109\0\u113a\0\u116b\0\u119c\0\u11cd\0\u11fe"+
    "\0\u122f\0\61\0\u1260\0\u1291\0\u12c2\0\u12f3\0\u1324\0\u1355"+
    "\0\u1386\0\u13b7\0\u13e8\0\u1419\0\u144a\0\u0e2a\0\u147b\0\u14ac"+
    "\0\u14dd\0\u150e\0\u153f\0\u1570\0\61\0\61\0\u15a1\0\u15d2"+
    "\0\61\0\u1603\0\u1634\0\u1665\0\u1696\0\u16c7\0\u16f8\0\u1729"+
    "\0\u175a\0\u178b\0\u17bc\0\u17ed\0\u181e\0\u184f\0\u1880\0\61"+
    "\0\61\0\u18b1\0\u18e2\0\61\0\u1913\0\u1944\0\u1975\0\61"+
    "\0\u19a6\0\u19d7\0\u1a08\0\u1a39\0\u1a6a\0\u1a9b\0\61\0\61"+
    "\0\61\0\u1acc\0\u1afd\0\61\0\u1b2e\0\61\0\u1b5f\0\u1b90"+
    "\0\u1bc1\0\61\0\u1bf2\0\u1c23\0\u1c54\0\u1c85\0\u1cb6\0\61"+
    "\0\u1ce7\0\61\0\u1d18\0\u1d49\0\61\0\u1d7a\0\u1dab\0\u1ddc"+
    "\0\u1e0d\0\u1e3e\0\u1e6f\0\u1ea0\0\u1ed1\0\u1f02\0\u1f33\0\u1f64"+
    "\0\u1f95\0\61\0\u1fc6\0\u1ff7\0\u2028\0\u2059\0\u208a\0\u20bb"+
    "\0\u20ec\0\u211d\0\u214e\0\u217f\0\u21b0\0\61\0\u21e1\0\u20bb"+
    "\0\u2212\0\u2243\0\u2274\0\u22a5\0\61\0\u22d6\0\u2307\0\61"+
    "\0\61\0\u2338\0\u2369\0\u2369";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[228];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\2\1\3\1\4\1\5\2\2\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\2\14\1\15\1\16"+
    "\1\17\1\20\7\2\1\21\1\22\1\23\1\24\2\2"+
    "\1\25\1\2\1\26\1\27\1\30\1\2\1\31\1\32"+
    "\1\33\1\2\1\34\1\2\1\35\2\2\63\0\1\3"+
    "\65\0\1\36\1\37\14\0\2\37\1\40\1\0\30\37"+
    "\1\0\2\41\1\0\1\41\1\42\54\0\2\43\1\0"+
    "\1\43\1\44\54\0\2\45\1\0\1\45\1\46\54\0"+
    "\2\47\1\0\1\47\1\50\7\0\1\51\1\0\2\14"+
    "\57\0\2\52\41\0\2\53\1\0\1\53\1\54\4\0"+
    "\1\55\3\0\1\56\57\0\1\52\1\0\2\14\5\0"+
    "\1\57\7\0\1\57\23\0\2\60\1\0\1\60\1\61"+
    "\14\0\1\62\1\63\57\0\1\64\37\0\2\65\1\0"+
    "\1\65\1\66\14\0\1\67\45\0\1\70\1\71\14\0"+
    "\2\71\1\72\1\0\30\71\44\0\1\73\2\0\1\74"+
    "\47\0\1\75\10\0\1\76\1\0\1\77\2\0\1\100"+
    "\50\0\1\101\1\0\1\102\2\0\1\103\5\0\1\104"+
    "\55\0\1\105\43\0\1\106\6\0\1\107\54\0\1\110"+
    "\50\0\1\111\64\0\1\112\66\0\1\113\2\0\1\114"+
    "\43\0\1\115\14\0\1\116\4\0\1\117\57\0\1\120"+
    "\2\0\1\121\52\0\1\122\51\0\1\123\17\0\2\124"+
    "\1\0\2\124\1\0\53\124\1\37\7\0\1\37\6\0"+
    "\2\37\4\0\2\37\2\0\30\37\30\0\1\125\32\0"+
    "\1\41\60\0\1\43\60\0\1\45\60\0\1\47\75\0"+
    "\2\52\5\0\1\57\7\0\1\57\24\0\1\53\56\0"+
    "\12\126\1\127\46\126\2\56\1\3\2\56\1\4\53\56"+
    "\13\0\2\130\2\0\2\131\42\0\1\60\57\0\2\132"+
    "\1\0\1\132\1\133\54\0\2\134\1\0\1\134\1\135"+
    "\54\0\2\136\1\0\1\136\1\137\55\0\1\65\57\0"+
    "\2\140\1\0\1\140\1\141\53\0\2\142\1\0\2\142"+
    "\1\0\53\142\1\71\7\0\1\71\6\0\2\71\4\0"+
    "\2\71\2\0\30\71\30\0\1\143\66\0\1\144\66\0"+
    "\1\145\47\0\1\146\100\0\1\147\54\0\1\150\61\0"+
    "\1\151\62\0\1\152\43\0\1\153\55\0\1\154\70\0"+
    "\1\155\64\0\1\156\51\0\1\157\67\0\1\160\65\0"+
    "\1\161\45\0\1\162\67\0\1\163\66\0\1\164\51\0"+
    "\1\165\56\0\1\166\62\0\1\167\44\0\1\170\60\0"+
    "\1\171\63\0\1\172\65\0\1\173\26\0\1\174\14\0"+
    "\2\174\2\0\30\174\12\126\1\175\60\126\1\175\3\126"+
    "\1\176\42\126\17\0\2\131\42\0\1\132\60\0\1\134"+
    "\60\0\1\136\60\0\1\140\66\0\1\177\14\0\2\177"+
    "\2\0\30\177\32\0\1\200\75\0\1\201\65\0\1\202"+
    "\35\0\1\203\77\0\1\204\56\0\1\205\50\0\1\206"+
    "\53\0\1\207\101\0\1\210\61\0\1\211\41\0\1\212"+
    "\1\213\65\0\1\214\54\0\1\215\63\0\1\216\72\0"+
    "\1\217\25\0\1\220\100\0\1\221\64\0\1\222\45\0"+
    "\1\223\63\0\1\224\74\0\1\225\42\0\1\226\72\0"+
    "\1\227\14\0\1\174\7\0\1\174\6\0\2\174\4\0"+
    "\2\174\2\0\30\174\12\126\1\175\3\126\1\3\42\126"+
    "\1\177\7\0\1\177\6\0\2\177\4\0\2\177\2\0"+
    "\30\177\51\0\1\230\60\0\1\231\47\0\1\232\72\0"+
    "\1\233\54\0\1\234\51\0\1\235\2\0\1\236\13\0"+
    "\1\237\40\0\1\240\54\0\1\241\64\0\1\242\101\0"+
    "\1\243\21\0\1\244\71\0\1\245\47\0\1\246\65\0"+
    "\1\247\71\0\1\250\70\0\1\251\64\0\1\252\51\0"+
    "\1\253\63\0\1\254\65\0\1\255\43\0\1\256\53\0"+
    "\1\257\71\0\1\260\72\0\1\261\43\0\1\262\62\0"+
    "\1\263\63\0\1\264\53\0\1\265\4\0\1\266\52\0"+
    "\1\267\47\0\1\270\67\0\1\271\51\0\1\272\67\0"+
    "\1\273\55\0\1\274\65\0\1\275\55\0\1\276\105\0"+
    "\1\277\46\0\1\300\54\0\1\301\62\0\1\302\15\0"+
    "\1\303\60\0\1\304\114\0\1\305\55\0\1\306\77\0"+
    "\1\307\61\0\1\310\57\0\1\311\45\0\1\312\57\0"+
    "\1\313\67\0\1\314\15\0\1\315\60\0\1\303\6\0"+
    "\1\316\14\0\2\316\2\0\30\316\1\0\1\304\6\0"+
    "\1\317\14\0\2\317\2\0\30\317\7\0\1\320\115\0"+
    "\1\321\56\0\1\322\60\0\1\323\54\0\1\324\60\0"+
    "\1\325\60\0\1\326\23\0\1\315\6\0\1\327\14\0"+
    "\2\327\2\0\30\327\1\316\7\0\1\316\6\0\2\316"+
    "\4\0\2\316\2\0\30\316\1\317\7\0\1\317\6\0"+
    "\2\317\4\0\2\317\2\0\30\317\2\330\1\0\2\330"+
    "\1\0\53\330\44\0\1\331\64\0\1\332\70\0\1\333"+
    "\32\0\1\334\65\0\1\335\21\0\1\327\7\0\1\327"+
    "\6\0\2\327\4\0\2\327\2\0\30\327\1\0\1\336"+
    "\132\0\1\337\43\0\1\340\65\0\1\341\16\0\1\336"+
    "\6\0\1\342\14\0\2\342\2\0\30\342\1\0\1\343"+
    "\57\0\1\342\7\0\1\342\6\0\2\342\4\0\2\342"+
    "\2\0\30\342\2\344\1\0\2\344\1\0\53\344";

  private static int [] zzUnpackTrans() {
    int [] result = new int[9114];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\32\1\1\0\1\1\1\0\1\11\1\1"+
    "\1\11\1\1\1\11\1\1\1\11\1\1\1\0\1\1"+
    "\1\11\1\1\1\0\1\1\1\0\1\11\1\1\3\0"+
    "\1\11\1\1\2\0\1\1\14\0\1\11\15\0\1\1"+
    "\4\0\1\1\1\11\1\1\1\11\1\1\1\11\1\1"+
    "\1\11\2\1\6\0\1\1\10\0\1\11\11\0\1\1"+
    "\1\0\2\1\4\0\1\1\2\11\2\0\1\11\3\0"+
    "\1\1\1\0\1\1\5\0\1\1\2\0\2\11\2\0"+
    "\1\11\3\0\1\11\6\0\3\11\2\0\1\11\1\0"+
    "\1\11\3\0\1\11\5\0\1\11\1\0\1\11\2\0"+
    "\1\11\14\0\1\11\3\0\2\1\6\0\1\11\2\1"+
    "\4\0\1\11\2\0\2\11\1\1\1\0\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[228];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
  enum sym {
                WHILE,
                END_WHILE,
                IF,
                ELSE,
                END_IF,
                FUNDEF,
                FUNDEL,
                END_FUNDEF,
                DEBUG_BREAK,
                EXIT,
                FUNCALL,
                JAVA_MATH_CALL,
                RUN_SCRIPT,
                NEG,
                DUP,
                DUPN,
                DROP,
                DROPN,
                SWAP,
                SWAPN,
                ROLLN,
                CLEAR,
                UPDATE,
                STACK_SIZE,
                RANGE,
                POV3D,
                COLOR,
                ERASE,
                PLOT,
                PLOT3D,
                LINE,
                LINE3D,
                DOT_SIZE,
                PUSH_IDENTIFIER,
                POP_IDENTIFIER,
                PUSH_ARRAY_VALUE,
                POP_ARRAY_VALUE,
                DOUBLE_LITERAL,
                DISPLAY_MESSAGE,
                PROMPT_MESSAGE,
                INFIXED,
                SUB,
                ADD,
                DIV,
                MUL,
                MOD,
                NEQ,
                EQ,
                LT,
                LTE,
                GT,
                GTE,
                EOF,
                SYNTAX_ERROR
  };

  final static int FUNDEF_LEN = new String("fundef").length();
  final static int FUNDEL_LEN = new String("fundel").length();
  final static int FUNCALL_LEN = new String("funcall").length();
  final static int MATH_CALL_LEN = new String("math_call").length();
  final static int RUN_SCRIPT_LEN = new String("run_script").length();
  final static int PUSH_VAR_LEN = new String("!").length();
  final static int POP_VAR_LEN = new String("?").length();
  final static int PUSH_ARRAY_LEN = new String("![]").length();
  final static int POP_ARRAY_LEN = new String("?[]").length();
  final static int DISPLAY_MESSAGE_LEN = new String("!\"").length();
  final static int PROMPT_MESSAGE_LEN = new String("?\"").length();
  final static int INFIXED_LEN = new String("infixed\"").length();

  String identifier = null;
  String filename = null;
  Double doubleValue = null;

  public int yyline() {
      return yyline;
  }

  public int yycolumn() {
      return yycolumn;
  }

  public int yychar() {
      return (int)yychar;
  }

  private Symbol symbol(sym type) {
    return new Symbol(type.ordinal(), yyline, yycolumn);
  }
  private Symbol symbol(sym type, Object value) {
    return new Symbol(type.ordinal(), yyline, yycolumn, value);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public ScriptLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(sym.EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return symbol(sym.SYNTAX_ERROR);
            }
            // fall through
          case 55: break;
          case 2:
            { /* ignore */
            }
            // fall through
          case 56: break;
          case 3:
            { try {doubleValue = new Double(yytext());} catch (Exception e) {doubleValue = Double.NaN;} return symbol(sym.DOUBLE_LITERAL);
            }
            // fall through
          case 57: break;
          case 4:
            { identifier = yytext().substring(PUSH_VAR_LEN).trim(); return symbol(sym.PUSH_IDENTIFIER);
            }
            // fall through
          case 58: break;
          case 5:
            { return symbol(sym.MOD);
            }
            // fall through
          case 59: break;
          case 6:
            { return symbol(sym.MUL);
            }
            // fall through
          case 60: break;
          case 7:
            { return symbol(sym.ADD);
            }
            // fall through
          case 61: break;
          case 8:
            { return symbol(sym.SUB);
            }
            // fall through
          case 62: break;
          case 9:
            { return symbol(sym.DIV);
            }
            // fall through
          case 63: break;
          case 10:
            { return symbol(sym.LT);
            }
            // fall through
          case 64: break;
          case 11:
            { return symbol(sym.GT);
            }
            // fall through
          case 65: break;
          case 12:
            { identifier = yytext().substring(POP_VAR_LEN).trim(); return symbol(sym.POP_IDENTIFIER);
            }
            // fall through
          case 66: break;
          case 13:
            { return symbol(sym.IF);
            }
            // fall through
          case 67: break;
          case 14:
            { identifier = yytext().substring(DISPLAY_MESSAGE_LEN).trim(); return symbol(sym.DISPLAY_MESSAGE);
            }
            // fall through
          case 68: break;
          case 15:
            { return symbol(sym.LTE);
            }
            // fall through
          case 69: break;
          case 16:
            { return symbol(sym.NEQ);
            }
            // fall through
          case 70: break;
          case 17:
            { return symbol(sym.EQ);
            }
            // fall through
          case 71: break;
          case 18:
            { return symbol(sym.GTE);
            }
            // fall through
          case 72: break;
          case 19:
            { identifier = yytext().substring(PROMPT_MESSAGE_LEN).trim(); return symbol(sym.PROMPT_MESSAGE);
            }
            // fall through
          case 73: break;
          case 20:
            { return symbol(sym.DUP);
            }
            // fall through
          case 74: break;
          case 21:
            { return symbol(sym.NEG);
            }
            // fall through
          case 75: break;
          case 22:
            { identifier = yytext().substring(PUSH_ARRAY_LEN).trim(); return symbol(sym.PUSH_ARRAY_VALUE);
            }
            // fall through
          case 76: break;
          case 23:
            { identifier = yytext().substring(POP_ARRAY_LEN).trim(); return symbol(sym.POP_ARRAY_VALUE);
            }
            // fall through
          case 77: break;
          case 24:
            { return symbol(sym.DROP);
            }
            // fall through
          case 78: break;
          case 25:
            { return symbol(sym.DUPN);
            }
            // fall through
          case 79: break;
          case 26:
            { return symbol(sym.ELSE);
            }
            // fall through
          case 80: break;
          case 27:
            { return symbol(sym.EXIT);
            }
            // fall through
          case 81: break;
          case 28:
            { return symbol(sym.LINE);
            }
            // fall through
          case 82: break;
          case 29:
            { return symbol(sym.PLOT);
            }
            // fall through
          case 83: break;
          case 30:
            { return symbol(sym.SWAP);
            }
            // fall through
          case 84: break;
          case 31:
            { return symbol(sym.CLEAR);
            }
            // fall through
          case 85: break;
          case 32:
            { return symbol(sym.COLOR);
            }
            // fall through
          case 86: break;
          case 33:
            { return symbol(sym.DROPN);
            }
            // fall through
          case 87: break;
          case 34:
            { return symbol(sym.ERASE);
            }
            // fall through
          case 88: break;
          case 35:
            { return symbol(sym.POV3D);
            }
            // fall through
          case 89: break;
          case 36:
            { return symbol(sym.RANGE);
            }
            // fall through
          case 90: break;
          case 37:
            { return symbol(sym.ROLLN);
            }
            // fall through
          case 91: break;
          case 38:
            { return symbol(sym.SWAPN);
            }
            // fall through
          case 92: break;
          case 39:
            { return symbol(sym.WHILE);
            }
            // fall through
          case 93: break;
          case 40:
            { return symbol(sym.END_IF);
            }
            // fall through
          case 94: break;
          case 41:
            { return symbol(sym.LINE3D);
            }
            // fall through
          case 95: break;
          case 42:
            { return symbol(sym.PLOT3D);
            }
            // fall through
          case 96: break;
          case 43:
            { return symbol(sym.UPDATE);
            }
            // fall through
          case 97: break;
          case 44:
            { return symbol(sym.DOT_SIZE);
            }
            // fall through
          case 98: break;
          case 45:
            { identifier = yytext().substring(FUNDEF_LEN).trim(); return symbol(sym.FUNDEF);
            }
            // fall through
          case 99: break;
          case 46:
            { identifier = yytext().substring(FUNDEL_LEN).trim(); return symbol(sym.FUNDEL);
            }
            // fall through
          case 100: break;
          case 47:
            { return symbol(sym.END_WHILE);
            }
            // fall through
          case 101: break;
          case 48:
            { identifier = yytext().substring(FUNCALL_LEN).trim(); return symbol(sym.FUNCALL);
            }
            // fall through
          case 102: break;
          case 49:
            { identifier = yytext().substring(INFIXED_LEN).trim(); return symbol(sym.INFIXED);
            }
            // fall through
          case 103: break;
          case 50:
            { return symbol(sym.END_FUNDEF);
            }
            // fall through
          case 104: break;
          case 51:
            { return symbol(sym.STACK_SIZE);
            }
            // fall through
          case 105: break;
          case 52:
            { return symbol(sym.DEBUG_BREAK);
            }
            // fall through
          case 106: break;
          case 53:
            { identifier = yytext().substring(MATH_CALL_LEN).trim(); return symbol(sym.JAVA_MATH_CALL);
            }
            // fall through
          case 107: break;
          case 54:
            { filename = yytext().substring(RUN_SCRIPT_LEN).trim(); return symbol(sym.RUN_SCRIPT);
            }
            // fall through
          case 108: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
